#! /bin/sh
set -e

# Disable CD image in sources.list if any other sources are present
if ([ -e /cdrom/.disk/base_installable ] || [ "$OVERRIDE_BASE_INSTALLABLE" ]) && \
   grep -q "^deb \(ht\|f\)tp" /target/etc/apt/sources.list; then
	logger -t finish-install "Disabling CD in sources.list"
	sed -i "/^deb cdrom:/s/^/#/" /target/etc/apt/sources.list
fi

COPY_LIST="/etc/apt/sources.list"
for f in $COPY_LIST ; do
	if  [ -r  "$f" ] ; then
		cp "$f" "/target/$f"
	fi
done

