#!/bin/sh
# -------
# File:        aurex-system-transmute
# Description: Install required sytem trasmutation level
# Author:      Luis Antonio Garcia Gisbert <luisgg@gmail.com> 
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along 
# with this program; if not, write to the Free Software Foundation, Inc., 
# 51 Franklin St, Fifth Floor, Boston MA 02110-1301 USA
# --------

# vars
# ----

# funcs
# -----

die(){
	echo "$1" >&2
	exit 1
}

usage(){
	die "Usage: $(basename "$0") {none|minimal|medium|full|get-level|update-level|pkg-update|pkg-remove}"
}

do_apt(){
        apt-get update || true
        apt-get --force-yes -y --allow-unauthenticated dist-upgrade || true
}

set_level_none(){
	update_level "none"
	aurex-transmute untransmute || true
	do_apt
}

set_level_minimal(){
	update_level "minimal"
	aurex-transmute untransmute || true
	aurex-transmute transmute keys
	TMPFILE="$(tempfile)"
        cp -a /etc/apt/sources.list "$TMPFILE"
	:> "$TMPFILE"
	sed -e "s%_@_UBUNTU_MIRROR_@_%$UBUNTU_MIRROR%g;s%_@_AUREX_MIRROR_@_%$AUREX_MIRROR%" /usr/share/aurex/templates/transmute/etc/apt/aurex-sources.list >> "$TMPFILE"
	mv "$TMPFILE" /etc/apt/sources.list.d/aurex-sources.list
	do_apt
}

set_level_medium(){
	update_level "medium"
	aurex-transmute untransmute || true
	aurex-transmute transmute keys || true
	aurex-transmute --module=apt-preferences transmute || true
	do_apt
}

set_level_full(){
	update_level "full"
	aurex-transmute transmute || true
	do_apt
}

say_level(){
	echo "$1"
	exit 0
}
get_level(){
	[ ! -r "$AUREX_TR_LEVEL" ] || say_level "$(head -1 "$AUREX_TR_LEVEL")"
	# try to guess ...
	[ ! -r /etc/apt/preferences.d/aurex-ubuntu-meta ] || say_level "full"
	[ ! -r /etc/apt/sources.list.d/aurex-sources.list ] || say_level "minimal"
	[ ! -r /etc/apt/preferences.d/aurex-ubuntu ] || say_level "medium"
	say_level "none"
}

update_level(){
	CURRENT_LEVEL=""
	[ ! -r "$AUREX_TR_LEVEL" ] || CURRENT_LEVEL="$(head -1 "$AUREX_TR_LEVEL")"
	if [ "$1" ] ; then
		NEW_LEVEL="$1"
	else
		NEW_LEVEL="$(get_level)"
	fi
	[ "$NEW_LEVEL" = "$CURRENT_LEVEL" ] || echo "$NEW_LEVEL" > "$AUREX_TR_LEVEL"
}


pkg_script(){
	update_level
	CURRENT_LEVEL="$(get_level)"
	case "$CURRENT_LEVEL" in
		minimal)
			aurex-transmute --module=transmute "$1" keys || true
			;;
		medium)
			aurex-transmute --module=transmute "$1" keys || true
			aurex-transmute --module=apt-preferences "$1" || true
			;;
		full)
			aurex-transmute --module=transmute "$1" || true
			;;
	esac
}


# main

TR_BASE_DIR="/usr/share/aurex-transmute"
if [ -r /etc/aurex/profile.sh ] ; then
	. /etc/aurex/profile.sh
else
	. $TR_BASE_DIR/transmute/base-files/etc/aurex/profile.sh
fi
UBUNTU_MIRROR=${UBUNTU_FORCEMIRROR:-$UBUNTU_DEFMIRROR}
AUREX_MIRROR=${AUREX_FORCEMIRROR:-$AUREX_DEFMIRROR}
AUREX_TR_LEVEL="/etc/aurex/system-transmute"

[ "$1" ] || usage

case "$1" in
	none)
		set_level_none
		;;
	minimal)
		set_level_minimal
		;;
	medium)
		set_level_medium
		;;
	full)
		set_level_full
		;;
	get-level)
		get_level
		;;
	update-level)
		update_level
		;;
	pkg-update)
		pkg_script transmute
		;;
	pkg-remove)
		pkg_script untransmute
		;;
	*)
		usage
		;;
esac

exit 0

