#!/bin/sh

set -e

# functions

die(){
	[ -z "$1" ] || echo "$1"
	exit 1
}

list_mirrors(){
	sed -ne  "/$SOURCES_REGEX/s%$SOURCES_REGEX%\1%p" "$@"
}

list_dists(){
	sed -ne  "/$SOURCES_REGEX/s%$SOURCES_REGEX%\2%p" "$@"
}

list_components(){
	sed -ne  "/$SOURCES_REGEX/s%$SOURCES_REGEX%\3%p" "$@" |tr " " "\n"
}

sed_rules(){
        for v in $(sed -ne "/^[^=]\+=/s%=.*$%%;p" ./aurex-meta.conf) ; do
                V="$(eval "echo $(eval "echo -n '$';echo -n $v")")"
                echo "s%_@_${v}_@_%${V}%g;"
        done
}

expand_variables(){
	sed_rules |sed -f - "$1" > "$2"
}

clean_sources(){
	expand_sources "" "clean"
}

expand_sources(){
	TARGET_DIR="$SOURCES_BASEDIR/"
	if [ "$1" ]; then
		TARGET_DIR="${1%/}/"
	fi
	# expand sources.list
	[ -d "$SOURCES_BASEDIR" ] || die

	if [ "$2" = "clean" ] ; then
		echo "clean sources.list templates"
	else
		echo "expand templates for sources.list"
	fi
	for f in $SOURCES_BASEDIR/*.in ; do
		if [ -r $f ] ; then
			F="${TARGET_DIR}$(basename "$f" ".in")"
			if [ "$2" = "clean" ] ; then
				rm -f "$F"
			else
				expand_variables "$f" "$F"
			fi
		fi
	done
}

expand_update_cfg(){
	# get mirror list and exceptions
	echo "get mirrors, dists and components"
	SOURCES_FILE="$(tempfile)"
	sed -ne "/$SOURCES_REGEX/p" $SOURCES_BASEDIR/*.list |sort -u > $SOURCES_FILE
	MIRROR_LIST="$(list_mirrors $SOURCES_FILE |sort -u)"
	DIST_LIST="$(list_dists $SOURCES_FILE |sort -u)"
	COMP_LIST="$(list_components $SOURCES_FILE |sort -u)"

	echo "get exceptions"
	EXCEPT_FILE="$(tempfile)"
	for m in $MIRROR_LIST ; do
		for d in $DIST_LIST ; do
			reg_ex="^deb[[:blank:]]\+$m[[:blank:]]\+$d"
			if grep -q "$reg_ex[[:blank:]]\+" $SOURCES_FILE; then
				for c in $COMP_LIST ; do
					if ! grep -q "${reg_ex}.*[[:blank:]]$c\([[:blank:]]\|$\)" "$SOURCES_FILE" ; then
						echo "${m%/}/,$d,$c" >> $EXCEPT_FILE
					fi
				done
			else
				echo "${m%/}/,$d" >> $EXCEPT_FILE
			fi
		done
	done
	ARCHIVE_URL_LIST="$UBUNTU_MIRROR"
	for m in $MIRROR_LIST; do
		[ "$m" = "$UBUNTU_MIRROR" ] || ARCHIVE_URL_LIST="$ARCHIVE_URL_LIST,${m%/}/"
	done

	ARCHIVE_EXCEPTIONS="$(cat "$EXCEPT_FILE" |tr "\n" " ")"

	rm $SOURCES_FILE $EXCEPT_FILE

	echo "expand update.cfg"
	expand_variables "update.cfg.in" "update.cfg"
}

update_seeds(){
	TMP_DIR="$(mktemp -d)"
	echo "Downloading seeds from launchpad ..."
	bzr branch $BZR_DIST $TMP_DIR/bzr-ubuntu.$CURRENT_DIST
	bzr branch $BZR_PLAT $TMP_DIR/bzr-platform.$CURRENT_DIST

	TIME_STAMP="$(date "+%Y%m%d-%H%M%S")"
	for d in ubuntu platform ; do
		rsync -axC $TMP_DIR/bzr-$d.$CURRENT_DIST/ $TMP_DIR/$d.$CURRENT_DIST/
		FIRST_TIME=""
		if [ ! -d "seeds/$d.$CURRENT_DIST" ] ; then
			mkdir -p "seeds/$d.$CURRENT_DIST"
			FIRST_TIME=Y
		fi
		rsync -axC seeds/$d.$CURRENT_DIST/ $TMP_DIR/current-$d.$CURRENT_DIST/
		if ! diff -qr $TMP_DIR/current-$d.$CURRENT_DIST $TMP_DIR/$d.$CURRENT_DIST  >/dev/null ; then
			if [ "$FIRST_TIME" ] ; then
				echo "$d.$CURRENT_DIST: No previous seeds found. Copying seeds for first time"
			else
				echo "$d.$CURRENT_DIST: Some changes detected. Updating local seeds ..."
				mkdir -p seeds/$d.$CURRENT_DIST.$TIME_STAMP
				rsync -axC seeds/$d.$CURRENT_DIST/ seeds/$d.$CURRENT_DIST.$TIME_STAMP/
				echo "$d.$CURRENT_DIST: OLD seeds stored in $d.$CURRENT_DIST.$TIME_STAMP as backup."
			fi
			rsync -axC --delete $TMP_DIR/$d.$CURRENT_DIST/ seeds/$d.$CURRENT_DIST/
			echo "$d.$CURRENT_DIST: updated."
		else
			echo "$d.$CURRENT_DIST: No changes found"
		fi
	done
	rm -fr $TMP_DIR
}

configure_sources(){
	expand_sources
	expand_update_cfg
}

configure_chroot(){
	TMP_DIR="$(mktemp -d)"
	cp $SOURCES_BASEDIR/*.list $TMP_DIR
	expand_sources "$TMP_DIR"
	TMP_SOURCES="$(tempfile)"
	cat $TMP_DIR/*.list > "$TMP_SOURCES"
	rm -rf "$TMP_DIR"
	CHROOT_SOURCES_LIST="$TMP_SOURCES"
}

test_debootstrap(){
	# TODO : ...
	[ -d "$CHROOT_DIR" ] && [ -x "$CHROOT_DIR/bin/sh" ] || die "Invalid debootstrap dir"
}

do_debootstrap(){
	rm -fr "$CHROOT_DIR"
	mkdir -p "$CHROOT_DIR"
	debootstrap "$CURRENT_DIST" "$CHROOT_DIR"
}

chroot_mounts(){
	mount --bind /dev "$CHROOT_DIR/dev"
	mount --bind /dev/pts "$CHROOT_DIR/dev/pts"
	mount --bind /proc/ "$CHROOT_DIR/proc"
	mount --bind /sys/ "$CHROOT_DIR/sys"

}

chroot_umounts(){
	umount "$CHROOT_DIR/dev/pts"
	umount "$CHROOT_DIR/dev"
	umount "$CHROOT_DIR/proc"
	umount "$CHROOT_DIR/sys"
}

prepare_chroot(){
	CHROOT_CMD="chroot $CHROOT_DIR "
	if [ "$CUSTOM_DEBOOTSTRAP_SOURCESLIST" ] && [ -r "$CUSTOM_DEBOOTSTRAP_SOURCESLIST" ] ; then
		CHROOT_SOURCES_LIST="$CUSTOM_DEBOOTSTRAP_SOURCESLIST"
	fi
	if [ "$CHROOT_SOURCES_LIST" ] && [ -r "$CHROOT_SOURCES_LIST" ] ; then
		echo "chroot: copy sources.list"
		cat "$CHROOT_SOURCES_LIST" > "$CHROOT_DIR/etc/apt/sources.list"
	fi
	if [ "$CUSTOM_DEBOOTSTRAP_COPY" ] && [ -d "$CUSTOM_DEBOOTSTRAP_COPY" ] ; then
		echo "chroot: copy custom files"
		rsync -axC "$CUSTOM_DEBOOTSTRAP_COPY/" "$CHROOT_DIR/"
	fi
	chroot_mounts
	CURRENT_LC_ALL="$LC_ALL"
	CURRENT_LANG="$LANG"
	export LC_ALL=C
	export LANG=C
	if [ "$CUSTOM_DEBOOTSTRAP_PKGS" ] ; then
		echo "chroot: install custom pkgs"
		$CHROOT_CMD apt-get update || true
		$CHROOT_CMD apt-get --allow-unauthenticated -y install "$CUSTOM_DEBOOTSTRAP_PKGS" || true
	fi
	if [ "$CUSTOM_DEBOOSTRAP_CMD" ] ; then
		echo "chroot: run custom cmd"
		$CHROOT_CMD $CUSTOM_DEBOOSTRAP_CMD || true
	fi
	echo "chroot: update & dist-upgrade"
	$CHROOT_CMD apt-get update || true 
	$CHROOT_CMD apt-get --allow-unauthenticated -y dist-upgrade || true
	chroot_umounts
	export LC_ALL=$CURRENT_LC_ALL
	export LANG=$CURRENT_LANG
	echo "chroot: end preparation"
}

usage(){
	die "Usage: $(basename "$0") {configure-sources|clean-sources|update-seeds|update-metapackages|debootstrap|prepare-chroot|update-lists|clean}"
}

# variables
. ./aurex-meta.conf
SOURCES_BASEDIR=./sources
SOURCES_REGEX="^deb[[:blank:]]\+\([^[:blank:]]\+\)[[:blank:]]\+\([^[:blank:]]\+\)[[:blank:]]\+\(.*\)$"

CHROOT_SOURCES_LIST=""
# main

case "$2" in
	--current-target=*)
		CHROOT_DIR="${2#*=}"
		;;
esac

case "$1" in
	configure-sources)
		configure_sources
		;;
	clean)
		clean_sources
		rm -f update.cfg
		;;
	update-seeds)
		update_seeds
		;;
	prepare-chroot)
		[ "$CHROOT_DIR" ] || die "prepare-chroot requires --current-target=<DIRNAME> option"
		configure_chroot
		test_debootstrap
		prepare_chroot
		;;
	update-metapackages)
		configure_sources
		germinate-update-metapackage --multiple-dists
		;;
	debootstrap)
		[ "$CHROOT_DIR" ] || die "debootstrap requires --current-target=<DIRNAME> option"
		[ $(id -u) -eq 0 ] || die "root privileges required"
		configure_chroot
		do_debootstrap
		prepare_chroot
		;;
	update-lists)
		[ $(id -u) -eq 0 ] || die "root privileges required"
		configure_chroot
		if [ -z "$CHROOT_DIR" ] ; then
			CHROOT_DIR="$(mktemp -d)"
			CLEAN_DIR="$CHROOT_DIR"
			do_debootstrap
		fi
		test_debootstrap
		prepare_chroot
		update_lists
		[ -z "$CLEAN_DIR" ] || rm -rf "$CLEAN_DIR"
		;;
	*)
		usage
		;;
esac
exit 0

