#!/bin/sh
# --------------------------------------------------------
# File:		vt-backup
# Description:	simple virtual machine backup script
# Authors:	Sandra Villanueva <svillanueva@ausiasmarch.net>
		Luis Garcia <lgarcia@ausiasmarch.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along 
# with this program; if not, write to the Free Software Foundation, Inc., 
# 51 Franklin St, Fifth Floor, Boston MA 02110-1301 USA
# --------------------------------------------------------


# vars
# -----
VIRSH_OPTIONS=""
VIRSH="virsh $VIRSH_OPTIONS"

# functions
# ---------

vt_get_disk_images(){
	VM_NAME="$1"
	$VIRSH dumpxml "$VM_NAME" |sed -ne "/<source file=/s%^.*'\(.*\)'.*$%\1%p"
}

vt_freeze_images(){
	TIMESTAMP="$(date "+%F_%H%M")"
	
	VM_DISK="$1"
	
	qemu-img -b 
}

