#!/bin/sh
# -------
# File:        aurex-notify-exec
# Description: aurex-notify backend
# Author:      Luis Garcia Gisbert <luisgg@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston MA 02110-1301 USA
# --------


set -e
#ICON_FILE="/usr/share/pixmaps/aurex/aurex-logo.svg"
ICON_FILE="distributor-logo"
LOGOUT_TIMEOUT=20
MESSAGE_CMD="notify-send -u normal -t $(($LOGOUT_TIMEOUT * 1000)) -i $ICON_FILE 'aurex-notify'"
LOGOUT_MESSAGE="Su sesión se cerrará en $LOGOUT_TIMEOUT segundos"

DEFAULT_OPTIONS="/etc/default/aurex-notify"
[ ! -r "$DEFAULT_OPTIONS" ] || . ${DEFAULT_OPTIONS}

message(){
   $MESSAGE_CMD "$1" 2>/dev/null
}

case $1 in
   MESSAGE)
      shift
      if [ "$1" ] ; then
         message "$*"
      fi
      ;;
#   LOGOUT)
#      message "$LOGOUT_MESSAGE"
#      sleep $LOGOUT_TIMEOUT
#      kdesktop=`ps -C kdesktop`
#      if [ $? -eq 0 -a -f /usr/bin/dcop ];then
#          dcop ksmserver default logout 0 -1 -1
#      else
#          gnome-session-save --kill --silent
#      fi
#      ;;
   ASK)
      shift
      case "$1" in
         "--regexp=*")
            REGEXP="${1#--regexp=}"
            shift
            ;;
      esac
      VALIDR=""
      while [ -z "$VALIDR" ] ; do
         ( sleep 1; wmctrl -v -a "aurex-notify" -b add,modal,above ; ) &
         R="$({ echo -n "--text=$*"; echo -n "\0000" ; } |xargs -0 zenity  --entry --title "aurex-notify" --window-icon=distributor-logo)"
         if [ -z "$REGEXP" ] || echo "$R" |grep -q "$REGEXP" ; then
            VALIDR=Y
         fi
      done
      echo "$R"
      ;;
   OPEN)
      shift
      if [ "$1" ] ; then
         [ -x /usr/bin/gnome-open ] && gnome-open "$*" 2>/dev/null
      fi
      ;;
esac
exit 0
