#!/bin/sh
# -------
# File:        aurex-notify-script
# Description: aurex-notify session script
# Author:      Luis Garcia Gisbert <luisgg@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston MA 02110-1301 USA
# --------

LIB_FILE="/usr/share/aurex-notify/aurex-notify-common.sh"
[ -r "$LIB_FILE" ] || exit 1
. ${LIB_FILE}
EXEC_SCRIPT="/usr/share/aurex-notify/aurex-notify-exec"

UNIX_SOCKET="$(create_socket)" || exit 0
rm -f "${UNIX_SOCKET}.sock" "${UNIX_SOCKET}.pid"
faucet "${UNIX_SOCKET}.sock" --unix --daemon --pidfile "${UNIX_SOCKET}.pid" --in xargs ${EXEC_SCRIPT}
chmod  600 "${UNIX_SOCKET}.pid"
chmod  666 "${UNIX_SOCKET}.sock"
exit 0
