#!/bin/sh
set -e
FNAME="aurex-logos/aurex-sunrise.svg"
DPI="266.70"
CMND="inkscape --without-gui --file=$FNAME --export-dpi=$DPI"
IDS="sun_glow space_glow planet_black planet_glow distro_logo distro_name"

case "$1" in
	clean)
		rm -f install/*
		;;
	*)
		for ID in $IDS ; do
			$CMND --export-id-only --export-id=$ID --export-png=install/$ID.png
		done
		cp ../space-sunrise-logo.script install/space-sunrise.script
		cp aurex-sunrise.plymouth install/
		;;
esac

exit 0

