#!/bin/sh
# repo-tools incoming hook script
# run all the scripts (linked) at /etc/repo-tools/hook-scripts.d
#


run-parts /etc/repo-tools/hook-scripts.d -a $1 -a "$(readlink -f "./incoming/$1")"

exit 0
