#!/bin/sh
# -------
# File:        aurex-transmute-gui
# Description: Select the transmutation level
# Author:      Luis Antonio Garcia Gisbert <luisgg@gmail.com> 
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along 
# with this program; if not, write to the Free Software Foundation, Inc., 
# 51 Franklin St, Fifth Floor, Boston MA 02110-1301 USA
# --------

#TODO: Find a real programmer to write a real gui for aurex ...

# vars
# ----

MAIN_TITLE="System Transmutation (aurex ... and beyond)"
ZEN_CMD="zenity --title $MAIN_TITLE"

# funcs
# -----

die(){
	$ZEN_CMD --error --text "$1"
	exit 1
}

# main

exit 0
