#!/bin/bash
# -------
# File:        aurex-transmute-gui
# Description: Select the transmutation level
# Author:      Luis Antonio Garcia Gisbert <luisgg@gmail.com> 
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along 
# with this program; if not, write to the Free Software Foundation, Inc., 
# 51 Franklin St, Fifth Floor, Boston MA 02110-1301 USA
# --------

#TODO: Find a real programmer to write a real gui for aurex ...

# vars
# ----

export TEXTDOMAIN="aurex-transmute"
MAIN_TITLE="$(gettext "System Transmutation (aurex ... and beyond)")"
MENU_TEXT="$(gettext "Select desired Transmutation level")"
declare -a MENU_RET=( "none" "minimal" "medium" "full" )
declare -a MENU_OPT=( \
"$(gettext "None")" \
"$(gettext "Minimal")" \
"$(gettext "Medium")" \
"$(gettext "Full")" \
 )

declare -a MENU_DES=( \
"$(gettext "Remove all the aurex customization")" \
"$(gettext "Add aurex repository to 'sources.list.d' (like a 'ppa')")" \
"$(gettext "Modify 'sources.list' and and set apt pinning to enable aurex, proposed and backports")" \
"$(gettext "Add repositories, artwork themes and metapackages")" \
 )

declare -a MENU_TIT=( \
"$(gettext "Select")" \
"$(gettext "Hide")" \
"$(gettext "Transmutation level")" \
"$(gettext "Description")" \
)

DEFAULT_OPT=1

# funcs
# -----

die(){
	zenity --title "$MAIN_TITLE" --error --text "$1"
	exit 1
}

confirm_msg(){
	TXT_MSG="$(gettext "Selected aurex level:") ${MENU_OPT[$1]}"
	TXT_MSG="$TXT_MSG. $(gettext "Do you want to update your system?")" 
	if zenity --title "$MAIN_TITLE" --question --text "$TXT_MSG" ; then
		return 0
	fi
	return 1
}

info_msg(){
	zenity --title "$MAIN_TITLE" --info --text "$1"

}

zsay(){
	echo -ne "$1\0000"
}

menu_options(){
	i=0
	while [ $i -lt ${#MENU_TIT[@]} ] ; do
		zsay "--column"
		zsay "${MENU_TIT[$i]}"
		i=$(($i + 1))
	done
	i=0
	while [ $i -lt ${#MENU_DES[@]} ] ; do
		if [ "$CURRENT_LEVEL" = "${MENU_RET[$i]}" ] ; then
			zsay "TRUE"
		else
			zsay "FALSE"
		fi
		zsay "$i"
		zsay "${MENU_OPT[$i]}"
		zsay "${MENU_DES[$i]}"
		i=$(($i + 1))
	done
}

show_menu(){
	menu_options |xargs -0 zenity --width=750 --height=300 --text "$MENU_TEXT" --title "$MAIN_TITLE" --list --radiolist --print-column=2 --hide-column=2 || echo "-1"
}

# main
CURRENT_LEVEL="$(aurex-upgrade get-level)"
menu_item=$(show_menu)
if [ $menu_item -ge 0 ] & [ $menu_item -lt ${#MENU_RET[@]} ] ; then
	if confirm_msg $menu_item ; then
		aurex-upgrade "${MENU_RET[$i]}" |zenity --auto-close --progress --pulsate || true
		info_msg "$(gettext "Transmutation completed")"
	fi
fi
	
echo $menu_item
exit 0
