#!/bin/sh
# -------
# File:        aurex-transmute
# Description: Transmute plain Ubuntu into golden AureX
# Author:      Luis Antonio Garcia Gisbert <luisgg@gmail.com> 
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along 
# with this program; if not, write to the Free Software Foundation, Inc., 
# 51 Franklin St, Fifth Floor, Boston MA 02110-1301 USA
# --------

# vars
# ----
TR_BASE_DIR="/usr/share/aurex-transmute"

if [ -r /etc/aurex/profile.sh ] ; then
	. /etc/aurex/profile.sh
else
	. /usr/share/aurex/base-files/transmute/etc/aurex/profile.sh
fi

# funcs
# -----

die(){
	echo "$1" >&2
	exit 1
}

usage(){
	die "Usage: $(basename "$0") [options] {test|transmute|untransmute|list-modules} [{all|sources|files|preseed|packages|keys|diversions|reconfigure} ...]\n\
       Options: --force\n\
                 --module=IDENTIFIER_NAME,...\n\
                 --no-sources --no-files --no-preseed --no-packages -no-keys --no-diversions --no-reconfigure"
}


test_release(){
	LSB_RELEASE="/usr/bin/lsb_release"
	if [ -x "$LSB_RELEASE" ] && [ "$($LSB_RELEASE -rs)" = "$AUREX_RELEASE" ] ; then
		return 0
	fi
	return 1
}

test_id(){
	[ $(id -u) -eq 0 ] || return 1
	return 0
}

test_aurex_sources(){
	grep -q "^deb[[:blank:]]\+[^[:blank:]]\+/aurex/\?[[:blank:]]\+$AUREX_CODENAME[[:blank:]]\+main" /etc/apt/sources.list || return 1
	return 0
}

test_ubuntu_sources(){
	for d in "" "-security" "-updates" "-proposed" "-backports" ; do
		for c in main restricted universe multiverse ; do
			if ! grep -q "^deb[[:blank:]]\+[^[:blank:]]\+[[:blank:]]\+$UBUNTU_CODENAME$d[[:blank:]]\+.*\b$c\($\|[[:blank:]]\)" /etc/apt/sources.list ; then
				echo "$UBUNTU_CODENAME$d $c: not found" >&2
				return 1
			fi
		done
	done
	if ! grep -q "^deb[[:blank:]]\+[^[:blank:]]\+[[:blank:]]\+$UBUNTU_CODENAME[[:blank:]]\+partner\($\|[[:blank:]]\)" /etc/apt/sources.list ; then
		echo "$UBUNTU_CODENAME$d partner: not found"
                return 1
	fi
	return 0
}	

test_onekey(){
	if [ -r "$1" ]; then
		F="$(basename "$1" ".gpg")"
		KEY_ID="${F##*.}"
		apt-key list |grep -q "/$KEY_ID[[:blank:]]" || return 1
	fi
	return 0
}

list_modules(){
	ls -1 $TR_BASE_DIR 2>/dev/null
}

test_keys(){
	[ "$BASE_NAME_LIST" ] || BASE_NAME_LIST="$(list_modules)"
	for pdir in $BASE_NAME_LIST ; do
		PDIR="$TR_BASE_DIR/$pdir/keys"
		if [ -d "$PDIR" ]; then
			for f in $PDIR/*.gpg ; do
				test_onekey "$f" || return $?
			done
		fi
	done
	return 0
}

get_ubuntu_mirror(){
	sed -ne "/^deb[[:blank:]]\+.*\.archive\.ubuntu\.com\/ubuntu\/\?[[:blank:]]\+$UBUNTU_CODENAME[[:blank:]]\+/{s%^deb[[:blank:]]\+%%;s%\(/ubuntu/\?\)[[:blank:]]\+$UBUNTU_CODENAME[[:blank:]]\+.*$%\1%;p}" /etc/apt/sources.list |head -1
}

trans_base_files(){
	[ "$BASE_NAME_LIST" ] || BASE_NAME_LIST="$(list_modules)"
	for pdir in $BASE_NAME_LIST ; do
		PDIR="$TR_BASE_DIR/$pdir/base-files/"
		if [ -d "$PDIR" ]; then
			rsync -ax "$PDIR" /
		fi
	done
}

untrans_base_files(){
	[ "$BASE_NAME_LIST" ] || BASE_NAME_LIST="$(list_modules)"
	for pdir in $BASE_NAME_LIST ; do
		PDIR="$TR_BASE_DIR/$pdir/base-files/"
		( cd "$PDIR" 2>/dev/null && find  -xtype f -exec  rm "/{}" \; || true ; )
	done
}

trans_sources(){
	[ -z "$BASE_NAME_LIST" -o "$BASE_NAME_LIST" = "transmute" ] || return 0
	TMPFILE="$(tempfile)"
	cp -a /etc/apt/sources.list "$TMPFILE"
	UBUNTU_MIRROR="$(get_ubuntu_mirror)"
	[ "$UBUNTU_MIRROR" ] || UBUNTU_MIRROR="$UBUNTU_DEFMIRROR"
	UBUNTU_MIRROR=${UBUNTU_FORCEMIRROR:-$UBUNTU_MIRROR}
	AUREX_MIRROR=${AUREX_FORCEMIRROR:-$AUREX_DEFMIRROR}
	sed -e "s%_@_UBUNTU_MIRROR_@_%$UBUNTU_MIRROR%g;s%_@_AUREX_MIRROR_@_%$AUREX_MIRROR%" /usr/share/aurex/templates/transmute/etc/apt/sources.list > "$TMPFILE"
	TIMESTAMP="$(date "+%Y%m%d.%H%M%S")"
	[ "$FORCE" ] || cp /etc/apt/sources.list /etc/apt/sources.list.aurex.$TIMESTAMP
	mv "$TMPFILE" /etc/apt/sources.list
}

untrans_sources(){
	[ -z "$BASE_NAME_LIST" -o "$BASE_NAME_LIST" = "transmute" ] || return 0
	FIRST_SOURCES="$(ls -1 /etc/apt/sources.list.aurex.* 2>/dev/null |sort |head -1)"
	[ "$FIRST_SOURCES" ] || FIRST_SOURCES=/usr/share/aurex/transmute/templates/etc/apt/sources.list.ubuntu
	cp "$FIRST_SOURCES" /etc/apt/sources.list
}

trans_preseed(){
	[ "$BASE_NAME_LIST" ] || BASE_NAME_LIST="$(list_modules)"
	for pdir in $BASE_NAME_LIST ; do
		PDIR="$TR_BASE_DIR/$pdir/preseed"
		if [ -d "$PDIR" ]; then
			for f in $PDIR/*.cfg ; do
				[ ! -r "$f" ] || debconf-set-selections "$f"
			done
		fi
	done
}

trans_packages(){
	UPDATE_REQUIRED=""
	[ "$BASE_NAME_LIST" ] || BASE_NAME_LIST="$(list_modules)"
	for pdir in $BASE_NAME_LIST ; do
		PDIR="$TR_BASE_DIR/$pdir/packages"
		if [ -d "$PDIR" ]; then
			for f in $PDIR/*.pkg ; do
				[ ! -r "$f" ] || dpkg --set-selections < "$f"
				UPDATE_REQUIRED="Y"
			done
		fi
	done
	if [ "$UPDATE_REQUIRED" ] ; then
		apt-get update && apt-get -y dselect-upgrade || return $?
	fi
}

trans_keys(){
	[ "$BASE_NAME_LIST" ] || BASE_NAME_LIST="$(list_modules)"
	for pdir in $BASE_NAME_LIST ; do
		PDIR="$TR_BASE_DIR/$pdir/keys"
		if [ -d "$PDIR" ]; then
			for f in $PDIR/*.gpg ; do
				if ! test_onekey "$f" ; then
					if apt-key add "$f" >/dev/null 2>/dev/null ; then
						F="$(basename "$f")"
						mkdir -p /var/lib/aurex/keys/$pdir
						touch /var/lib/aurex/keys/$pdir/$F
					else
						return $?
					fi
				fi
			done
		fi
	done
}

untrans_keys(){
	[ "$BASE_NAME_LIST" ] || BASE_NAME_LIST="$(list_modules)"
	for pdir in $BASE_NAME_LIST ; do
		PDIR="/var/lib/aurex/keys/$pdir"
		if [ -d "$PDIR" ]; then
			for f in $PDIR/*.gpg ; do
				F="$(basename "$f" ".gpg")"
				KEY_ID="${F##*.}"
				apt-key del "$KEY_ID" >/dev/null 2>/dev/null || true
				rm "$f"
			done
		fi
	done
}


trans_divert(){
	[ "$BASE_NAME_LIST" ] || BASE_NAME_LIST="$(list_modules)"
	for pdir in $BASE_NAME_LIST ; do
		PDIR="$TR_BASE_DIR/$pdir/divert"
		if [ -d "$PDIR" ] ; then
			for f in $(find "$PDIR" -xtype f -printf "/%P\n") ; do
				if [ ! -e "${f}.aurex-divert" ] && dpkg-divert --package aurex-transmute --rename --quiet --add --divert ${f}.aurex-divert ${f} || [ "$FORCE" ] ; then
					cp "${PDIR}${f}" "${f}"
				fi
			done
		fi
	done
}

untrans_divert(){
	[ "$BASE_NAME_LIST" ] || BASE_NAME_LIST="$(list_modules)"
	for pdir in $BASE_NAME_LIST ; do
		PDIR="$TR_BASE_DIR/$pdir/divert"
		if [ -d "$PDIR" ] ; then
			for f in $(find "$PDIR" -xtype f -printf "/%P\n") ; do
				if [ -e "${f}.aurex-divert" ] ; then
					rm -f "$f"
					dpkg-divert --package aurex-transmute --rename --quiet --remove ${f} || true
				fi
			done
		fi
	done
}

trans_reconfigure(){
	[ "$BASE_NAME_LIST" ] || BASE_NAME_LIST="$(list_modules)"
	for pdir in $BASE_NAME_LIST ; do
		PDIR="$TR_BASE_DIR/$pdir/reconfigure"
		if [ -d "$PDIR" ]; then
			for f in $PDIR/*.pkg ; do
				for p in $(cat "$f") ; do
					if [ -r "/var/lib/dpkg/info/${p}.postinst" ] ; then
						dpkg-reconfigure --frontend noninteractive $p || true
					fi
				done
			done
		fi
	done
}

do_transmute(){
	test_id || die "Error: You must be root, my friend"
	test_release || die "Error: Invalid Ubuntu release"
	if [ "$TFILES" = "Y" ] ; then
		trans_base_files || die "Error: Unable to install AureX base-files"
	fi
	if [ "$TSOURCES" = "Y" ] && [ -z "$BASE_NAME_LIST" -o "$BASE_NAME_LIST" = "transmute" ] ; then
		if [ "$FORCE" ] || ! test_ubuntu_sources || ! test_aurex_sources  ; then
			trans_sources || die "Error: Unable to fix sources.list"
		fi
	fi
	if [ "$TPRESEED" = "Y" ] ; then
		trans_preseed || die "Error: Unable to load preseed"
	fi
	if [ "$TKEYS" = "Y" ] ; then
		if [ "$FORCE" ] || ! test_keys ; then
			trans_keys || die "Error: Unable to install gpg keys"
		fi
	fi
	if [ "$TPACKAGES" = "Y" ] ; then
		 trans_packages || die "Error: Unable to install packages"
	fi
	if [ "$TDIVERT" = "Y" ] ; then
		 trans_divert || die "Error: Unable to divert files"
	fi
	if [ "$TRECONF" = "Y" ] ; then
		 trans_reconfigure || die "Error: Unable to reconfigure packages"
	fi


}

undo_transmute(){
	test_id || die "Error: You must be root, my friend"
	[ "$TSOURCES" = "N" ] || untrans_sources
	[ "$TFILES" = "N" ] || untrans_base_files
	[ "$TKEYS" = "N" ] || untrans_keys
	[ "$TDIVERT" = "N" ] || untrans_divert
	[ "$TRECONF" = "N" ] || trans_reconfigure
}

do_test(){
	test_rc=0
	if ! test_release ; then
		echo "Invalid Ubuntu release" >&2
		test_rc=1
	fi
	if [ "$TSOURCES" = "Y" ] && ! test_ubuntu_sources ; then
		echo "Invalid sources list: some Ubuntu components missing" >&2
		test_rc=$(($test_rc + 2))
	fi
	if [ "$TSOURCES" = "Y" ] && ! test_aurex_sources ; then
		echo "Invalid sources list: AureX component missing" >&2
		test_rc=$(($test_rc + 4))
	fi
	if [ "$TFILES" = "Y" ] ; then
		CURDIR="$(pwd)"
		FILELIST=$(cd /usr/share/aurex/base-files/etc/ 2>/dev/null && find  -xtype f)
		test_rc_files=0
		for f in $FILELIST ; do
			if [ ! -r "/etc/$f" ] ; then
				echo "file: /etc/$f not installed" >&2
				test_rc_files=8
			fi
		done
		test_rc=$(($test_rc + $test_rc_files))
	fi
	if [ "$TKEYS" = "Y" ] && ! test_keys ; then
		echo "gpg signin keys not installed" >&2
		test_rc=$(($test_rc + 16))
	fi
	[ $test_rc -ne 0 ] || echo "All your base are belong to AureX"
	return $test_rc
}

force_fixvars(){
	# when force is enabled, set required vars as dependencies
	if [ "$TDIVERT" = "Y" ] ; then
		TPACKAGES="Y"
	fi

	if [ "$TPACKAGES" = "Y" ] ; then
		TSOURCES="Y"
		TPRESEED="Y"
	fi
	if [ "$TSOURCES" = "Y" ] ; then
		TKEYS="Y"
		TFILES="Y"
	fi
}

# main
# ----

[ "$1" ] || usage
while [ -z "$END_PARAMETERS" ] ; do
	case "$1" in 
		--force)
			FORCE="Y"
			shift
			;;
		--no-sources)
			TSOURCES="N"
			shift
			;;
		 --no-files)
			TFILES="N"
			shift
			;;
		 --no-preseed)
			TPRESEED="N"
			shift
			;;
		 --no-packages)
			TPACKAGES="N"
			shift
			;;
		 --no-keys)
			TKEYS="N"
			shift
			;;
		 --no-diversions)
			TDIVERT="N"
			shift
			;;
		 --no-reconfigure)
			TRECONF="N"
			shift
			;;
		--module=*)
			BASE_NAME_LIST="${1#--module=}"
			BASE_NAME_LIST="$(echo "$BASE_NAME_LIST" |tr "," " ")"
			shift
			;;
		*)
			END_PARAMETERS="Y"
			;;
	esac
done

[ "$1" ] || usage
ACTION="$1"
shift
SUBACTION="all"
if [ "$1" ] ; then
	SUBACTION="$1"
	shift
fi

while [ "$SUBACTION" ] ; do
	[ "$SUBACTION" = "sources" -o "$SUBACTION" = "all" ] && TSOURCES=${TSOURCES:-Y}
	[ "$SUBACTION" = "files" -o "$SUBACTION" = "all" ] && TFILES=${TFILES:-Y}
	[ "$SUBACTION" = "preseed" -o "$SUBACTION" = "all" ] && TPRESEED=${TPRESEED:-Y}
	[ "$SUBACTION" = "packages" -o "$SUBACTION" = "all" ] && TPACKAGES=${TPACKAGES:-Y}
	[ "$SUBACTION" = "keys" -o "$SUBACTION" = "all" ] && TKEYS=${TKEYS:-Y}
	[ "$SUBACTION" = "diversions" -o "$SUBACTION" = "all" ] && TDIVERT=${TDIVERT:-Y}
	[ "$SUBACTION" = "reconfigure" -o "$SUBACTION" = "all" ] && TRECONF=${TRECONF:-Y}
	if [ "$1" ] ; then
		SUBACTION="$1"
		shift
	else
		SUBACTION=""
	fi

done
echo " $TSOURCES $TFILES $TPRESEED $TPACKAGES $TKEYS $TDIVERT $TRECONF" |grep -q "Y" || usage

[ -z "$FORCE" ] || force_fixvars

case "$ACTION" in
	test)
		do_test || exit $?
		;;
	transmute)
		do_transmute || exit $?
		;;
	untransmute)
		undo_transmute || exit $?
		;;
	list-modules)
		list_modules
		;;
	*)
		usage
		;;
esac

exit 0
